### PR TITLE
Border filter fix

### PR DESCRIPTION
**Pull request by sapant**
This branch is for the fix of isssue#6
 https://github.com/axet/jhlabs/issues/6

Please let me know if there are any questions

### CODE REVIEW

**Comment by axet** [comment]
Hi. Can you provide screenshots?

**Comment by sapant** [comment]
Please see below the screenshot

**Using existing BorderFilter without new fix**
beforefix

**Using updated BorderFilter**
afterfix

**Comment by axet** [comment]
Can you not change files not related to bug fix? (ie .gitignore) Even if it seems reasonable.

**Comment by sapant** [comment]
ok will revert the .gitignore

**Comment by sapant** [comment]
Done. reverted gitignore changes

**Comment by axet** [comment]
Thanks!

I'll upload new archive to the sonata, after few weeks. Maybe more bug fixes coming.

**Pull request merged**
